### ISSUE TITLE
(0.5) statsManager doesn't use same address url as clientPool

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#171]
Using 
```js
clientPool.options = {
    serverAddress: '192.168.1.170:4000',
}
```
And statsManager keeps sending statistics to production url

**Comment by carlosescri** [comment]
I think that's caused because the stats manager is created before you change the options and is not re-generated:

https://github.com/doofinder/webcomponents/blob/13eeb41fa6d5a08a5b75a044908b289118c00d69/packages/core/src/stats-manager.ts#L29

We could make the pool a singleton in the library and make `StatsClient` use it. I think it's rare to have more than one pool in an app, so the stats client would always get the client from the pool.

What do you think @sonic182?

**Comment by sonic182** [comment]
```ts
import { clientPool, ContextTopic } from '@dfwc/core';
// ...
clientPool.options = options.pool;
```

I do set options from imported clientPool, It is an constant inside doofinder-client.ts file

```ts
export const clientPool: ClientPool = new ClientPool();
```

I don't know if Singleton will help, it is an single variable already isn't it?
