### ISSUE TITLE
(1) Ensure when product click, statistics request resolves before redirect

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#176]
Actually may happen that user click's on a product and the register event may not be sent (because the answer is not waited in order to continue with the redirect)

It should be something like a promise that when resolved, does the redirect

**Comment by sonic182** [comment]
It actually should wait until all handlers are execute before being redirected (I don't know how).

If any event handler does `event.preventDefault()` it shouldn't do redirect

**Comment by sonic182** [comment]
A way to detect the last bubling event, it's to tie a listener at the `body` element which will be the last to bubble (or just `document` object or `<html>`)

**Comment by carlosescri** [comment]
To prevent redirection you must use: `event.detail.originalEvent.preventDefault()`. I think that case is handled.

**Comment by sonic182** [comment]
Oh yes, it worked

**Comment by carlosescri** [comment]
Results components are not connected to a context due to performance reasons: having 1,000 components that constantly change traversing the DOM to connect to a context that may never use is a waste of resources.

To account the stats in the result we could search for the context when we're handling the click and use it to get the stats manager and do the job and then go to the result url.
